### ISSUE TITLE
Error with Sequelize Injection of Tables/Limits

### ISSUE THREAD

**Issue by ptariche** [nodefluent/sequelize-kafka-connect#41]
https://github.com/nodefluent/sequelize-kafka-connect/blob/1f7871473dc42a21e41821d7d73f92177e8502f1/lib/source/SequelizeSourceTask.js#L50

Attempting to use the code out of the box with a mysql dialect, with a table known as users: I'm receiving the following error.

```
'You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near \'\'users\' ORDER BY \'id\' LIMIT 25 OFFSET 0\' at line 1',
```

@krystianity 

"sequelize-kafka-connect": "^3.6.0"

**Comment by krystianity** [comment]
Hi @ptariche  the table and column name looks wrong \'\'users\'  they shouldnt be in quotes.

**Comment by krystianity** [comment]
Will be fixed in the next release.
