### ISSUE TITLE
Enable passing additional options for table

### ISSUE THREAD

**Issue by holgeradam** [nodefluent/sequelize-kafka-connect#5]
Hey there,

the package works flawlessly so far. However one more thing would be very helpful.
Sequelize allows to create indexes for tables only by passing it via the options parameter in the define call. Currently I can only pass the schema which maps to the attributes parameter.

Would you be able to add another parameter to the createSinkSchemaConverter function that enables this behaviour?

Thanks!

**Comment by krystianity** [comment]
Hey @holgeradam, thanks for your request. "createSinkSchema" is now able to support an additional parameter "schemaAttributes", which should get you going :)
